### ISSUE TITLE
if  active fail, add error info to issue

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp-China/article-webpage-to-markdown-action#17]
**Is your feature request related to a problem? Please describe.（遇见的问题）**
A clear and concise description of what the problem is.（简单地描述问题）

**Describe the solution you'd like（描述想要的解决方案）**
A clear and concise description of what you want to happen.（简洁地描述你想要的解决方案。）
当action 运行失败， 把错误信息，添加到所创建的 issue， 方便别人定位问题。

**Additional context（其他）**
Add any other context about the problem here.（添加其他你想添加的内容）

**Comment by luojiyin1987** [comment]
https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow    不同action 传递 数据的方式方式找到了    直接往虚拟机里写入文件。
 
 但是怎么解决 把数据写到  issue 的  Comment 里  ?

**Comment by luojiyin1987** [comment]
关键词  `github action add comment to issue`  搜索到   
[一个 action](https://github.com/marketplace/actions/create-or-update-comment)
[文档](https://docs.github.com/en/actions/managing-issues-and-pull-requests/commenting-on-an-issue-when-a-label-is-added)  

@TechQuery    @stevending1st   还有其他思路？

**Comment by stevending1st** [comment]
> @TechQuery @stevending1st 还有其他思路？

可以参考 action 官方文档

**Comment by luojiyin1987** [comment]
https://github.com/ActionsDesk/add-comment-action   在这个项目找到灵感，在尝试中

**Comment by luojiyin1987** [comment]
[issues-create-comment](https://octokit.github.io/rest.js/v18#issues-create-comment) 
文档写出相关代码      https://github.com/luojiyin1987/article-webpage-to-markdown-action
主要逻辑

src/utilities.js
```js
exports.addComment = async (comment) =>{
  const githubToken = core.getInput("githubToken") || undefined;
  console.log("githubToken",githubToken)
  if(githubToken) {
    const octokit =  github.getOctokit(githubToken)
    const playload =  github.context.payload;
    const issue  = playload.issue;
    const repository = playload.repository;

    await octokit.rest.issues.createComment({
      owner: repository.owner.login,
      repo:  repository.name,
      body:comment,
      issue_number:issue.number,
   
    })
    core.debug(`issue: ${issue}`);
    core.debug(`repository: ${repository}`);
    core.debug(`comment: ${comment}`);
  } else {
    throw new Error('GitHub token was not found in environment');
  }
}
```

src/index.js 中
```js

  } catch (error) {
    console.log(error);
    addComment(error);
    process.exitCode = 1;
  }
```


[action 相关报错](https://github.com/luojiyin1987/try-action/actions/runs/2378529079)

**Comment by luojiyin1987** [comment]
[成功了](https://github.com/luojiyin1987/try-action/issues/58)  

 前出现的问题是，打包问题，导致一个函数出现几次，   dist/index.js 删除 重新打包，解决。

ts 的推导能力没想象那么强， 没有静态语言，在编译的时候就告诉你。

**Comment by TechQuery** [comment]
> ts 的推导能力没想象那么强， 没有静态语言，在编译的时候就告诉你。

开启 TS 严格模式试试
