### ISSUE TITLE
生成的markdown中 原文作者信息 有兩行空行

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp-China/article-webpage-to-markdown-action#2]
**Describe the bug（bug 描述）**
生成的markdown中 原文作者信息 有兩行空行
（用简单的语言描述 bug。）

**To Reproduce（复现方式）**

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/6524977/158954833-80894a6e-3504-4b68-8a57-c2ddc862aa99.png)

If applicable, add screenshots to help explain your problem.（可以截图辅助描述。）

**Comment by luojiyin1987** [comment]
解決办法
在 文件utilities.js 
```js
const authorName = authorCardName.text()
```
改为  
```js
const authorName = authorCardName.text().replace(/[\n ]/g, '')
```
同时过滤掉  `\n`  和空白字符

**Comment by stevending1st** [comment]
@luojiyin1987 既然已经 debug 了，为啥不提 PR。
