### ISSUE TITLE
网络差的情况下， 报`The DOM of the website has been modified, or there is a problem with loading, please confirm`

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp-China/article-webpage-to-markdown-action#8]
**Describe the bug（bug 描述）**
A clear and concise description of what the bug is.（用简单的语言描述 bug。）

**To Reproduce（复现方式）**
Steps to reproduce the behavior（复现 bug 的步骤）:
1. Go to '...'（访问“...”）
2. Click on '....'（点击“...”）
3. See bug（出现 bug）action 日志报   `The DOM of the website has been modified, or there is a problem with loading, please  confirm`
重新开 issue 进行爬虫   就没问题了， 初步推测应该是  GitHub 的服务器到 freecodecamp 的网络不稳定， 建议加入重试机制， 并限制好重试次数

**Comment by luojiyin1987** [comment]
@stevending1st   我在考虑是否要加入延时执行？

**Comment by stevending1st** [comment]
> @stevending1st 我在考虑是否要加入延时执行？

主要是要节约 action 资源
